MoviesApp/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MoviesApp.Models;
using NToastNotify;
using MoviesApp.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;                                                          
using System.Linq;
using System.Threading.Tasks;

namespace MoviesApp.Controllers
{
    public class MoviesController : Controller
    {
        private readonly MovieDbContext _context;
        private readonly IToastNotification _toastNotification;
        private List<string> _allowedExtentions = new List<string> { ".jpg", ".png" };
        private long _maxAllowedPoster = 1048576;
        public MoviesController ( MovieDbContext context, IToastNotification toastNotification )
        {
            _context = context;
            this._toastNotification = toastNotification;
        }
        public async Task<IActionResult> Index ( )
        {
            var movies = await _context.Movies.OrderByDescending ( m => m.Rate ).ToListAsync ( );
            return View ( movies );
        }
        public async Task<IActionResult> Create ( )
        {
            var viewModel = new MovieFormVM
            {
                Genres = await _context.Genres.OrderBy ( a => a.Name ).ToListAsync ( )
            };
            return View ( "MovieForm", viewModel );
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create ( MovieFormVM model )
        {
            if (!ModelState.IsValid)
            {
                model.Genres = await _context.Genres.OrderBy ( a => a.Name ).ToListAsync ( );
                return View ( "MovieForm", model );
            }

            var files = Request.Form.Files;
            if (!files.Any ( ))
            {
                model.Genres = await _context.Genres.OrderBy ( a => a.Name ).ToListAsync ( );
                ModelState.AddModelError ( "Poster", "Please Select Movie Poster!" );
                return View ( "MovieForm", model );

            }

            var poster = files.FirstOrDefault ( );

            if (!_allowedExtentions.Contains ( Path.GetExtension ( poster.FileName ).ToLower ( ) ))
            {
                model.Genres = await _context.Genres.OrderBy ( a => a.Name ).ToListAsync ( );
                ModelState.AddModelError ( "Poster", "Only .jpg and .png images are allowed!" );
                return View ( "MovieForm", model );
            }

            if (poster.Length > _maxAllowedPoster)
            {
                model.Genres = await _context.Genres.OrderBy ( a => a.Name ).ToListAsync ( );
                ModelState.AddModelError ( "Poster", "Poster Cannot be More than 1 MB !" );
                return View ( "MovieForm", model );
            }

            using var dataStream = new MemoryStream ( );
            await poster.CopyToAsync ( dataStream );

            var movies = new Movie ( )
            {
                Title = model.Title,
                GenreId = model.GenreId,
                Year = model.Year,
                Rate = model.Rate,
                StoreLine = model.StoreLine,
                Poster = dataStream.ToArray ( )
            };

            _context.Movies.Add ( movies );
            _context.SaveChanges ( );

            _toastNotification.AddSuccessToastMessage ( "Movie Created Successfully" );

            return RedirectToAction ( "Index" );
        }
        public async Task<IActionResult> Edit ( int? id )
        {
            if (id == null)
                return BadRequest ( );
            var movie = await _context.Movies.FindAsync ( id );
            if (movie == null)
                return NotFound ( );
            var viewModel = new MovieFormVM
            {
                id = movie.Id,
                Title = movie.Title,
                GenreId = movie.GenreId,
                Rate = movie.Rate,
                Year = movie.Year,
                StoreLine = movie.StoreLine,
                Poster = movie.Poster,
                Genres = await _context.Genres.OrderBy ( m => m.Name ).ToListAsync ( )

            };
            return View ( "MovieForm", viewModel );

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit ( MovieFormVM model )
        {
            if (!ModelState.IsValid)
            {
                model.Genres = await _context.Genres.OrderBy ( a => a.Name ).ToListAsync ( );
                return View ( "MovieForm", model );
            }

            var movie = await _context.Movies.FindAsync ( model.id );
            if (movie == null)
                return NotFound ( );

            var files = Request.Form.Files;
            if (files.Any ( ))
            {
                var poster = files.FirstOrDefault ( );
                using var datastream = new MemoryStream ( );
                await poster.CopyToAsync ( datastream );
                model.Poster = datastream.ToArray ( );
                if (!_allowedExtentions.Contains ( Path.GetExtension ( poster.FileName ).ToLower ( ) ))
                {
                    model.Genres = await _context.Genres.OrderBy ( a => a.Name ).ToListAsync ( );
                    ModelState.AddModelError ( "Poster", "Only .jpg and .png images are allowed!" );
                    return View ( "MovieForm", model );
                }

                if (poster.Length > _maxAllowedPoster)
                {
                    model.Genres = await _context.Genres.OrderBy ( a => a.Name ).ToListAsync ( );
                    ModelState.AddModelError ( "Poster", "Poster Cannot be More than 1 MB !" );
                    return View ( "MovieForm", model );
                }
                movie.Poster = model.Poster;
            }

            movie.Title = model.Title;
            movie.GenreId = model.GenreId;
            movie.Rate = model.Rate;
            movie.Year = model.Year;
            movie.StoreLine = model.StoreLine;

            _context.SaveChanges ( );

            _toastNotification.AddSuccessToastMessage ( "Movie Edited Successfully" );
            return RedirectToAction ( nameof ( Index ) );

        }
        public async Task<IActionResult> Details ( int? id )
        {
            if (id == null)
                return BadRequest ( );
            var movie = await _context.Movies.Include(m=>m.Genre).SingleOrDefaultAsync(m => m.Id == id);
            if (movie == null)
                return NotFound ( );
            return View ( movie );

        }
        public async Task<IActionResult> Delete(int? id)
        {
            if(id == null)
                return BadRequest();
            var movie = await _context.Movies.FindAsync(id);
            if(movie == null)
                return NotFound();
            _context.Movies.Remove(movie);
            _context.SaveChanges();
            return Ok();

        }
    }
}

MoviesApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MoviesApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet" />
    <link href="~/lib/animate.css/animate.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MoviesApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index">Movies</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MoviesApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="~/lib/bootbox.js/bootbox.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await Component.InvokeAsync("NToastNotify")
</body>
</html>